apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-app-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      type: postgres-app-pod
  template:
    metadata:
      labels:
        type: postgres-app-pod
    spec:
      containers:
      - name: postgres
        image: postgres
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "postgres"
        - name: POSTGRES_HOST_AUTH_METHOD
          value: trust
