apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-app-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      type: redis-app-pod
  template:
    metadata:
      labels:
        type: redis-app-pod
    spec:
      containers:
      - name: redis
        image: redis
        ports:
        - containerPort: 6379
