apiVersion: v1
kind: Service
metadata:
  name: voting-app-svc
spec:
  type: NodePort
  selector:
    type: voting-app-pod
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30004
    protocol: TCP
